title: Compile.work - Tutorials & Compilation Guides
description: >
  Tutorials and Compilation Guides for the Popular Programming Languages. Installing, Setup, Running the compiler Online as well as Offline.
baseurl: "/guides"
url: "http://127.0.0.1:4000" 
#url: "http://compile.work"
twitter_username: aroliant
github_username:  aroliant

markdown: kramdown
theme: minima

collections:
  docs:
    output: true
    permalink: /docs/:name/